name = "bricklayer-manager"
compatibility_date = "2026-05-02"
main = "api/worker.js"
account_id = "8851e575353a23f4511fbe2d1a74505e"

[assets]
directory = "./public"

[vars]
ADMIN_EMAIL = "admin@example.com"
ADMIN_PASSWORD = "password123"

send_email = [
  { name = "EMAIL_SENDER" }
]

[[d1_databases]]
binding = "BRICKLAYER_DB"
database_name = "bricklayer-db"
database_id = "e96a5716-ce7d-41d8-8018-9f8b62465d04"

[env.preview]
name = "bricklayer-manager-preview"

[triggers]
crons = ["0 0 * * *"]
