name = "bricklayer-manager"
compatibility_date = "2024-05-12"
main = "api/worker.js"

[assets]
directory = "./public"

[vars]
ADMIN_EMAIL = "admin@example.com"
ADMIN_PASSWORD = "password123"

[[kv_namespaces]]
binding = "BRICKLAYER_SITES"
id = "preview_namespace_id"
preview_id = "preview_namespace_id"

[env.preview]
name = "bricklayer-manager-preview"
